### PR TITLE
CRA-861: Fixed issue with reading xyz-surfaces in the case when area …

### PR DESCRIPTION
**Pull request by hgolsen**
…is taken from surface.

### CODE REVIEW

**Comment by alfbr** [comment]
Is this related to #254 or #255 ?

**Comment by hgolsen** [comment]
This is related to both. This is a general fix for reading xyz-surfaces, but tested on a simpler case. It is not certain that it fixes both these problems, so please re-run both cases when this pull-request is merged.

**Comment by alfbr** [comment]
Great, already downloaded and compiled. Will try to get it tested over here.

**Comment by alfbr** [comment]
PR tested. The inversion still fails, but it seems to fail in a different header file. This is the error message:

cravarun: ../libs/nrlib/surface/../grid/grid2d.hpp:147: size_t NRLib::Grid2D<A>::GetIndex(size_t, size_t) const [with A = double]: Assertion `j < nj_' failed.

**Comment by hgolsen** [comment]
Sorry. This was not merged (this was only a request for merging), so you did not have the updates. (There is usually a small delay from when a request is made to when it is merged into the master branch.)

I have merged the commit into the master branch now. Can you test again tomorrow?

**Comment by alfbr** [comment]
I am not completely ignorant ;-) I forked your repository, and double checked that this commit was in there before I compiled:

$ git log
commit 403f6c5901416fa7026e44913e0e68ade8e648f2
Author: Håvard Goodwin Olsen <Havard.Olsen@nr.no>
Date:   Tue Feb 28 13:06:24 2017 +0100

    CRA-861: Fixed issue with reading xyz-surfaces in the case when area is taken from surface.

**Comment by hgolsen** [comment]
Ah, okey :) I didn't think of that option. Then these issues are still unresolved.

**Comment by alfbr** [comment]
Yes, I believe so. You have the datasets, so please see if you can reproduce at your end.

**Pull request merged**
